#! /bin/bash

docker volume create postgres
docker run -d --name postgres \
    -e POSTGRES_USER=camel -e POSTGRES_PASSWORD=camel \
    -e POSTGRES_DB=cameldb \
    -v postgres:/var/lib/postgresql/data \
    -p 5432:5432 postgres:latest

