#! /bin/bash

app=${1:-exercise1}

export M2_HOME=$HOME/Software/apache-maven-3.9.9
export M2=$M2_HOME/bin
export PATH=$M2:$PATH

mvn -version
mvn archetype:generate -DgroupId=training -DartifactId=${app} -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.5 -DinteractiveMode=false

